package constants

const (
	ENUM_ROLE_ADMIN = "admin"
	ENUM_ROLE_GUEST = "guest"

	ENUM_AUDIENCE_REGULAR = "regular"
	ENUM_AUDIENCE_INVITED = "invited"

	ENUM_SPONSORSHIP_CATEGORY_SPONSOR       = "sponsor"
	ENUM_SPONSORSHIP_CATEGORY_PARTNER       = "partner"
	ENUM_SPONSORSHIP_CATEGORY_MEDIA_PARTNER = "media partner"

	ENUM_MERCH_CATEGORY_TSHIRT  = "t-shirt"
	ENUM_MERCH_CATEGORY_CAP     = "cap"
	ENUM_MERCH_CATEGORY_STICKER = "sticker"
	ENUM_MERCH_CATEGORY_OTHER   = "other"

	ENUM_MIDTRANS_STATUS_PENDING    = "pending"
	ENUM_MIDTRANS_STATUS_SETTLEMENT = "settlement"
	ENUM_MIDTRANS_STATUS_FAILURE    = "failure"
	ENUM_MIDTRANS_STATUS_EXPIRE     = "expire"
	ENUM_MIDTRANS_STATUS_CANCEL     = "cancel"
	ENUM_MIDTRANS_STATUS_DENY       = "deny"
	ENUM_MIDTRANS_STATUS_REFUND     = "refund"

	ENUM_MIDTRANS_PAYMENT_TYPE_BANK_TRANSFER = "bank_transfer"
	ENUM_MIDTRANS_PAYMENT_TYPE_CREDIT_CARD   = "credit_card"
	ENUM_MIDTRANS_PAYMENT_TYPE_QRIS          = "qris"
	ENUM_MIDTRANS_PAYMENT_TYPE_GOPAY         = "gopay"
	ENUM_MIDTRANS_PAYMENT_TYPE_SHOPEE        = "shopeepay"

	ENUM_MIDTRANS_ACQUIRE_MANDIRI = "mandiri"
	ENUM_MIDTRANS_ACQUIRE_BRI     = "bri"
	ENUM_MIDTRANS_ACQUIRE_BCA     = "bca"
	ENUM_MIDTRANS_ACQUIRE_BNI     = "bni"
	ENUM_MIDTRANS_ACQUIRE_CIMB    = "cimb"

	ENUM_RUN_PRODUCTION = "production"
	ENUM_RUN_TESTING    = "testing"

	ENUM_PAGINATION_LIMIT = 10
	ENUM_PAGINATION_PAGE  = 1
)
