package constants

const (
	ENUM_ROLE_ADMIN = "admin"
	ENUM_ROLE_GUEST = "guest"

	ENUM_AUDIENCE_REGULAR = "regular"
	ENUM_AUDIENCE_INVITED = "invited"

	ENUM_INSTANSI_UNAIR = "unair"
	ENUM_INSTANSI_UMUM  = "umum"

	ENUM_SPONSORSHIP_CATEGORY_SPONSOR       = "sponsor"
	ENUM_SPONSORSHIP_CATEGORY_PARTNER       = "partner"
	ENUM_SPONSORSHIP_CATEGORY_MEDIA_PARTNER = "media partner"

	ENUM_MERCH_CATEGORY_TSHIRT  = "t-shirt"
	ENUM_MERCH_CATEGORY_CAP     = "cap"
	ENUM_MERCH_CATEGORY_STICKER = "sticker"
	ENUM_MERCH_CATEGORY_OTHER   = "other"

	ENUM_TICKET_ITEM_TYPE = "ticket"
	ENUM_MERCH_ITEM_TYPE  = "merch"
	ENUM_BUNDLE_ITEM_TYPE = "bundle"

	ENUM_BUNDLE_MERCH_TYPE        = "bundle merch"
	ENUM_BUNDLE_MERCH_TICKET_TYPE = "bundle merch ticket"

	ENUM_RUN_PRODUCTION = "production"
	ENUM_RUN_TESTING    = "testing"

	ENUM_PAGINATION_LIMIT = 10
	ENUM_PAGINATION_PAGE  = 1

	REFERAL_CODE = "TEDX2025"
)
