version: "3.9"

services:
  backend:
    build: .
    container_name: golang-backend-dev
    restart: always
    ports:
      - "8010:8010"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - backend_assets:/app/assets

volumes:
  backend_assets: {}
